// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	DeleteEntries(ctx context.Context, owner string) error
	DeleteEntry(ctx context.Context, id int32) error
	GetCategories(ctx context.Context) ([]sql.NullString, error)
	GetEntries(ctx context.Context, owner string) ([]Entry, error)
	GetEntry(ctx context.Context, arg GetEntryParams) (Entry, error)
	GetEntryForUpdate(ctx context.Context, arg GetEntryForUpdateParams) (Entry, error)
	UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error)
}

var _ Querier = (*Queries)(nil)
